### ISSUE TITLE
Unexpected <EOF> in GraphQL request

### ISSUE THREAD

**Issue by Davo911** [IBM/wxflows#3]
When going through the Question Answer example.
with the following `toml`:
```toml
[stepzen.cli]
endpoint = "wxflows-genai/Name"

[wxflows.deployment]
# Example flows.
flows="""
    // myPrompt = ragAnswerInput | topNDocs | promptFromTopN | ragInfo
    myRag = ragAnswerInput | topNDocs | promptFromTopN | completion(parameters:myRag.parameters) | ragInfo
    // myRagWithGuardrails = ragAnswerInput | topNDocs | promptFromTopN | completion(parameters:myRagWithGuardrails.parameters) | ragScoreInfo | hallucinationScore | ragScoreMessage | ragInfo
"""
ai_engine = "WATSONX"

[wxflows.deployment.source.aicore]
# RAG configuration
collection="ColName"
tsv_files = ["OwnSample.tsv"]
embedding_model="ibm/slate-30m-english-rtrvr"
data_type = "md"
data_directory = "./OwnSampleMds"
chunk_size = 500
chunk_overlap = 50
documentstore.type="milvusmt"
```

It's throwing the following Syntax Error:
```shell
wxflows collection deploy

Found flow definition in the configuration

Provisioning the watsonx.ai flows engine environment
Published flow myRag to https://***/wxflows-genai/***/graphql in 4.154s
Deploying the wxflows-genai/OwnSample endpoint... done

Creating or updating the KubevirtDocs1 collection
Using https://***/wxflows-genai/***/graphql for uploading into search engine type: milvusmt

Error: An error occurred while uploading data: Syntax Error: Unexpected <EOF>.

GraphQL request:1:1
1 |
  | ^
```
